name: Sync to Gitee
on: [push] # 当有 push 事件时触发
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/dushenyan
          dst: gitee/dushenyan
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "template" # 只同步这个仓库
          force_update: true # 启用强制同步，覆盖式更新